INSERT INTO `PRODUCT` (`NAME`, `TYPE`, `MANUFACTURER`, `PRICE`, `DESC`) VALUES ('Teszt termek', 'Teszt', 'Teszt gyarto', 1000, 'Valami');
INSERT INTO `PRODUCT` (`NAME`, `TYPE`, `MANUFACTURER`, `PRICE`, `DESC`) VALUES ('Teszt termek 2', 'Teszt', 'Teszt gyarto', 1500, 'Valami');
INSERT INTO `PRODUCT` (`NAME`, `TYPE`, `MANUFACTURER`, `PRICE`, `DESC`) VALUES ('Teszt termek 3', 'Teszt', 'Teszt gyarto', 2000, 'Valami');

INSERT INTO `MOHOSZ` (`CARD_ID`, `NAME`, `CARD_ISSUE`, `CARD_EXPIRATION`, `FISHING_LICENSE_NUMB`, `IS_DISABLED`) VALUES (123456, 'Teszt Nev', '2018-12-24', '2024-12-24', 000450, TRUE);
INSERT INTO `MOHOSZ` (`CARD_ID`, `NAME`, `CARD_ISSUE`, `CARD_EXPIRATION`, `FISHING_LICENSE_NUMB`, `IS_DISABLED`) VALUES (917286, 'Paldi Akos', '2018-10-12', '2024-10-12', 00453, FALSE);
INSERT INTO `MOHOSZ` (`CARD_ID`, `NAME`, `CARD_ISSUE`, `CARD_EXPIRATION`, `FISHING_LICENSE_NUMB`, `IS_DISABLED`) VALUES (654321, 'Teszt Nev2', '2019-01-14', '2025-01-14', 00456, FALSE);

INSERT INTO `CLUB` (`NAME`, `SHIRE`) VALUES ('Teszt Klub 1', 'Hajdú-Bihar');
INSERT INTO `CLUB` (`NAME`, `SHIRE`) VALUES ('Teszt Klub 2', 'Győr-Moson-Sopron');
INSERT INTO `CLUB` (`NAME`, `SHIRE`) VALUES ('Teszt Klub 3', 'Pest');